export const INIT_GENRES = 'INIT_GENRES';
export const INIT_AUTHORS = 'INIT_AUTHORS';
export const INIT_OPERATION = 'INIT_OPERATION';
export const UPDATE_OPERATION = 'UPDATE_OPERATION';
export const RESET_OPERATION = 'RESET_OPERATION';
export const CANCEL_OPERATION = 'CANCEL_OPERATION';
export const SELECT_NAVIGATION_TAB = 'SELECT_NAVIGATION_TAB';
