export const INIT_GENRES = 'INIT_GENRES';
export const VIEW_ACTION = 'VIEW_ACTION';
export const CHANGE_EVENT = 'CHANGE_EVENT';
export const SELECT_ITEM = 'SELECT_ITEM';
export const INIT_AUTHORS = 'INIT_AUTHORS';
export const INIT_BOOKS = 'INIT_BOOKS';
export const SELECT_NAVIGATION_TAB = 'SELECT_NAVIGATION_TAB';

export const NAVIGATION_TAB_GENRES = 'NAVIGATION_TAB_GENRES';
export const NAVIGATION_TAB_AUTHORS = 'NAVIGATION_TAB_AUTHORS';
export const NAVIGATION_TAB_BOOKS = 'NAVIGATION_TAB_BOOKS';